version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo-docker
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  gofile:
    build:
      context: ./api
    container_name: gofile
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - mongodb
  script:
    build:
      context: ./script
    container_name: script
    depends_on:
      - gofile
